export { getTenantDb, getPlatformDb, type TenantDb } from "./tenant";
export { setChunkEmbedding, searchChunks, type ChunkSearchResult } from "./vector";
export type {
  Role,
  Agency,
  Tenant,
  User,
  Location,
  LocationHours,
  Service,
  StaffMember,
  Customer,
  Lead,
  LeadStage,
  LeadSource,
  Tag,
  Conversation,
  ConversationChannel,
  ConversationStatus,
  Message,
  MessageSender,
  KnowledgeDocument,
  DocumentStatus,
  DocumentChunk,
  Prisma,
} from "./generated/prisma/client";
