export { getTenantDb, getPlatformDb, type TenantDb } from "./tenant";
export type {
  Role,
  Agency,
  Tenant,
  User,
  Location,
  LocationHours,
  Service,
  StaffMember,
  Customer,
  Lead,
  LeadStage,
  LeadSource,
  Tag,
  Conversation,
  ConversationChannel,
  ConversationStatus,
  Message,
  MessageSender,
  Prisma,
} from "./generated/prisma/client";
